# Service defined here, plus serviceName below in StatefulSet,
# are needed only because of condition explained in
# https://github.com/kubernetes/kubernetes/issues/69608

kind: Service
apiVersion: v1
metadata:
  name: csi-hostpathplugin
  labels:
    app: csi-hostpathplugin
spec:
  selector:
    app: csi-hostpathplugin
  ports:
    - name: dummy
      port: 12345
---
###
apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: hostpath-csi
#---
#kind: ClusterRole
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: hostpath-csi-role
#rules:
#  - apiGroups: [""]
#    resources: ["persistentvolumes"]
#    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
#  - apiGroups: [""]
#    resources: ["events"]
#    verbs: ["create", "get", "list", "watch", "update", "patch"]
#  - apiGroups: [""]
#    resources: ["persistentvolumeclaims"]
#    verbs: ["get", "list", "watch", "update", "patch"]
#  - apiGroups: [""]
#    resources: ["nodes"]
#    verbs: ["get", "list", "watch", "update", "patch"]
#  - apiGroups: ["storage.k8s.io"]
#    resources: ["storageclasses"]
#    verbs: ["get", "list", "watch"]
#  - apiGroups: ["storage.k8s.io"]
#    resources: ["volumeattachments"]
#    verbs: ["get", "list", "watch", "update", "patch"]
#  - apiGroups: [""]
#    resources: ["configmaps"]
#    verbs: ["get", "list", "watch", "create", "update", "patch"]
#---
#kind: ClusterRoleBinding
#apiVersion: rbac.authorization.k8s.io/v1#metadata:
#  name: hostpath-csi-role
#subjects:
#  - kind: ServiceAccount
#    name: hostpath-csi
#    namespace: default
#roleRef:
#  kind: ClusterRole
#  name: hostpath-csi-role
#  apiGroup: rbac.authorization.k8s.io
#---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-hostpathplugin-ds
spec:
  selector:
    matchLabels:
      app: csi-hostpathplugin
  template:
    metadata:
      labels:
        app: csi-hostpathplugin
    spec:
      hostNetwork: true
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi-hostpath /registration/csi-hostpath-reg.sock"]
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-hostpath/csi.sock
          securityContext:
            privileged: true
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          - mountPath: /registration
            name: registration-dir
          - mountPath: /csi-data-dir
            name: csi-data-dir

        - name: hostpath
          image: quay.io/k8scsi/hostpathplugin:v1.2.0-rc8
          args:
            - "--drivername=hostpath.csi.k8s.io"
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          ports:
          - containerPort: 9898
            name: healthz
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
              name: plugins-dir
            - mountPath: /csi-data-dir
              name: csi-data-dir

        - name: liveness-probe
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          args:
          - --csi-address=/csi/csi.sock
          - --connection-timeout=3s
          - --health-port=9898

      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
          name: plugins-dir
        - hostPath:
            # 'path' is where PV data is persisted on host.
            # using /tmp is also possible while the PVs will not available after plugin container recreation or host reboot
            path: /var/lib/csi-hostpath-data/
            type: DirectoryOrCreate
          name: csi-data-dir
